[package]
authors = ["Tommaso Pifferi <p.tommy93@gmail.com>"]
edition = "2018"
name = "mozjpeg-wasm"
version = "0.1.0"

[dependencies]
mozjpeg-sys = { version = "1.0.2", features = ["jpegtran"], default-features = false }
wee_alloc = "0.4.5"
